import React, { useState } from 'react';
import { 
  Activity, 
  Zap, 
  Eye, 
  Dna, 
  BrainCircuit, 
  Stethoscope, 
  ArrowRight, 
  Check, 
  Info,
  X 
} from 'lucide-react';

interface ExpertiseItem {
  id: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  clinicalDetails: string;
  typicalIndications: string[];
}

interface ExpertiseSectionProps {
  onSelectService?: (serviceName: string) => void;
  onOpenBooking: () => void;
}

export const ExpertiseSection: React.FC<ExpertiseSectionProps> = ({
  onSelectService,
  onOpenBooking,
}) => {
  const [selectedExpertise, setSelectedExpertise] = useState<ExpertiseItem | null>(null);

  const expertiseList: ExpertiseItem[] = [
    {
      id: 'eeg-brain',
      title: 'EEG & Brain Electrical Activity',
      description: 'Evaluation of electrical activity in the brain using electroencephalography and related neurophysiological techniques.',
      icon: Activity,
      clinicalDetails: 'Records bioelectrical potentials generated by the cerebral cortex. Non-invasive gold-standard procedure for assessing cortical rhythm continuity, focal slowing, and epileptiform discharges.',
      typicalIndications: ['Transient loss of consciousness', 'Unexplained confusion or delirium', 'Epileptiform discharge mapping', 'Sleep-related paroxysms']
    },
    {
      id: 'emg-ncs',
      title: 'EMG & Nerve Conduction Studies',
      description: 'Assessment of nerves and muscles to help investigate weakness, numbness, tingling, and other neuromuscular symptoms.',
      icon: Zap,
      clinicalDetails: 'Provides detailed physiological evaluation of both sensory and motor peripheral nerves, paired with concentric needle evaluation of skeletal muscle motor units.',
      typicalIndications: ['Carpal tunnel & tarsal tunnel syndrome', 'Peripheral polyneuropathy', 'Cervical / lumbar radiculopathies', 'Myasthenia gravis & junction testing']
    },
    {
      id: 'evoked-potentials',
      title: 'Evoked Potentials',
      description: 'Specialized neurophysiological testing used to evaluate how the nervous system responds to specific sensory stimulation.',
      icon: Eye,
      clinicalDetails: 'Quantifies conduction time along visual (VEP), auditory/brainstem (BAEP), and somatosensory (SSEP) tracts to uncover subclinical demyelination or central pathway lesions.',
      typicalIndications: ['Optic nerve dysfunction', 'Auditory pathway delays', 'Spinal sensory pathway evaluation', 'Demyelinating condition assessments']
    },
    {
      id: 'neuromuscular',
      title: 'Neuromuscular Evaluation',
      description: 'Assessment of conditions affecting peripheral nerves, muscles, and neuromuscular function.',
      icon: Dna,
      clinicalDetails: 'Dedicated protocols designed to assess the entire motor unit—from anterior horn cells down through peripheral axons, the neuromuscular junction, and muscle fibers.',
      typicalIndications: ['Progressive muscle weakness', 'Fasciculations and cramping', 'Motor neuron disease inquiries', 'Inherited or acquired myopathies']
    },
    {
      id: 'seizure-epilepsy',
      title: 'Seizure & Epilepsy Evaluation',
      description: 'Neurophysiological assessment that may assist in the evaluation of seizure-related conditions.',
      icon: BrainCircuit,
      clinicalDetails: 'Systematic qualitative and quantitative analysis of interictal and ictal electroencephalographic waveforms, aiding referring specialists in clinical classification.',
      typicalIndications: ['Suspected first-time seizures', 'Evaluation of recurrent paroxysmal events', 'Epilepsy classification support', 'Post-ictal electrographic verification']
    },
    {
      id: 'diagnostic-assessment',
      title: 'Neurological Diagnostic Assessment',
      description: 'Comprehensive assessment to support accurate neurological diagnosis and appropriate clinical management.',
      icon: Stethoscope,
      clinicalDetails: 'Holistic clinical synthesis combining electrophysiological findings with clinical presentation and symptom history for evidence-based care.',
      typicalIndications: ['Complex diagnostic inquiries', 'Second-opinion test reviews', 'Collaborative neurology referrals', 'Longitudinal neurophysiological monitoring']
    },
  ];

  return (
    <section id="expertise" className="py-20 md:py-28 bg-white text-slate-900 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Heading */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-xs font-bold uppercase tracking-wider text-teal-700 bg-teal-50 px-3 py-1 rounded-full border border-teal-200/60 inline-block mb-3">
            Core Disciplines
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Areas of Expertise
          </h2>
          <p className="mt-3 text-base text-slate-600 leading-relaxed">
            Specialized electrodiagnostic methodologies applied with rigorous scientific protocols to evaluate central and peripheral nervous system function.
          </p>
        </div>

        {/* 6 Elegant Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
          {expertiseList.map((item) => {
            const Icon = item.icon;
            return (
              <div
                key={item.id}
                className="group relative bg-[#FAFAFC] hover:bg-white rounded-2xl p-6 sm:p-7 border border-slate-200/80 hover:border-teal-500/50 shadow-sm hover:shadow-xl hover:shadow-teal-900/5 transition-all duration-300 flex flex-col justify-between"
              >
                <div>
                  {/* Refined Medical Icon */}
                  <div className="w-12 h-12 rounded-xl bg-teal-50 group-hover:bg-teal-500 text-teal-700 group-hover:text-white flex items-center justify-center transition-all duration-300 mb-5 shadow-xs">
                    <Icon className="w-6 h-6 stroke-[1.75]" />
                  </div>

                  {/* Card Title */}
                  <h3 className="text-lg font-bold text-slate-900 group-hover:text-teal-900 transition-colors">
                    {item.title}
                  </h3>

                  {/* Description (Exact prompt text) */}
                  <p className="mt-2.5 text-sm text-slate-600 leading-relaxed">
                    {item.description}
                  </p>
                </div>

                {/* Footer action */}
                <div className="mt-6 pt-4 border-t border-slate-100 flex items-center justify-between">
                  <button
                    onClick={() => setSelectedExpertise(item)}
                    className="inline-flex items-center gap-1.5 text-xs font-semibold text-teal-700 hover:text-teal-800 transition-colors cursor-pointer"
                  >
                    <span>View Clinical Details</span>
                    <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                  </button>

                  <span className="text-[11px] font-mono text-slate-400">
                    Clinical Protocol
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Responsible Notice */}
        <div className="mt-12 text-center text-xs text-slate-500 max-w-2xl mx-auto flex items-center justify-center gap-2">
          <Info className="w-4 h-4 text-teal-600 shrink-0" />
          <span>
            Assessments are conducted pursuant to clinical symptoms, medical history, and referring physician recommendations.
          </span>
        </div>

      </div>

      {/* Expertise Detail Modal */}
      {selectedExpertise && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm animate-fade-in">
          <div className="relative w-full max-w-lg bg-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-slate-200">
            <button
              onClick={() => setSelectedExpertise(null)}
              className="absolute top-5 right-5 p-2 rounded-full text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 flex items-center justify-center">
                <selectedExpertise.icon className="w-5 h-5" />
              </div>
              <div>
                <span className="text-[11px] font-bold uppercase tracking-wider text-teal-700">Expertise Profile</span>
                <h3 className="text-xl font-bold text-slate-900">{selectedExpertise.title}</h3>
              </div>
            </div>

            <p className="text-sm text-slate-600 leading-relaxed mb-5">
              {selectedExpertise.clinicalDetails}
            </p>

            <div className="space-y-2 mb-6">
              <p className="text-xs font-bold text-slate-900 uppercase tracking-wide">
                Common Clinical Inquiries:
              </p>
              <div className="grid grid-cols-1 gap-1.5">
                {selectedExpertise.typicalIndications.map((ind, i) => (
                  <div key={i} className="flex items-center gap-2 text-xs text-slate-700">
                    <Check className="w-3.5 h-3.5 text-teal-600 shrink-0" />
                    <span>{ind}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
              <button
                onClick={() => setSelectedExpertise(null)}
                className="px-4 py-2 rounded-xl text-xs font-medium text-slate-600 hover:bg-slate-100"
              >
                Close
              </button>
              <button
                onClick={() => {
                  setSelectedExpertise(null);
                  onOpenBooking();
                }}
                className="px-5 py-2.5 rounded-xl text-xs font-semibold text-slate-950 bg-teal-400 hover:bg-teal-300 transition-colors shadow-sm"
              >
                Request Assessment
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};
